version: '3.8'

services:
  rasa:
    image: rasa/rasa:3.6.2
    ports:
      - "5005:5005"
    volumes:
      - ./rasa_project:/app
    command: run --enable-api --cors "*"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
      - action_server

  action_server:
    build: ./actions
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    environment:
      - DATABASE_URL=${DATABASE_URL}

  retrain_pipeline:
    build: ./retrain_pipeline
    volumes:
      - ./retrain_pipeline:/app
      - ./rasa_project/data:/app/data
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
