name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements_enhanced.txt
          pip install -r requirements_web.txt

      - name: Run tests
        run: |
          python -m pytest test_local.py -v

      - name: Build Docker images (without push)
        run: |
          echo "Docker images would be built here in production"
          echo "Skipping Docker Hub push for now" 