name: Build, Test, and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements_enhanced.txt
          pip install -r requirements_web.txt

      - name: Run tests
        run: |
          python test_local.py

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        continue-on-error: true

      - name: Build and push rasa server
        uses: docker/build-push-action@v4
        with:
          context: ./backend/rasa_project
          file: ./backend/rasa_project/Dockerfile
          push: ${{ secrets.DOCKERHUB_USERNAME != '' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-chatbot-rasa:latest
        continue-on-error: true

      - name: Build and push action server
        uses: docker/build-push-action@v4
        with:
          context: ./backend/actions
          file: ./backend/actions/Dockerfile
          push: ${{ secrets.DOCKERHUB_USERNAME != '' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-chatbot-actions:latest
        continue-on-error: true

      - name: Check Docker Hub status
        run: |
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ] || [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "⚠️ Docker Hub secrets not configured"
            echo "Docker images were built but not pushed"
            echo "To enable Docker Hub pushes, add DOCKERHUB_USERNAME and DOCKERHUB_TOKEN secrets"
          else
            echo "✅ Docker images built and pushed successfully"
          fi 