name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push rasa server
        uses: docker/build-push-action@v4
        with:
          context: ./backend/rasa_project
          file: ./backend/rasa_project/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-chatbot-rasa:latest

      - name: Build and push action server
        uses: docker/build-push-action@v4
        with:
          context: ./backend/actions
          file: ./backend/actions/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-chatbot-actions:latest

      - name: Build and push retrain pipeline
        uses: docker/build-push-action@v4
        with:
          context: ./backend/retrain_pipeline
          file: ./backend/retrain_pipeline/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ai-chatbot-retrain:latest 